name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install SSH key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy the application
      - name: Deploy with PM2
        run: |
          ssh -o StrictHostKeyChecking=no -T ${{ secrets.SSH_URL }} "cd $HOME/projects/kanbased/backend && git pull origin main && pnpm install && pnpm run build && pm2 reload ecosystem.config.js && pm2 save"
