name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Install SSH key
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Go to projects folder"
            cd $HOME/projects/kanbased/backend || exit

            echo "Pull latest changes"
            git pull origin main || exit

            echo "Installing dependencies"
            pnpm install || exit

            echo "Removing old dist folder"
            rm -rf ./dist

            echo "Running migrations"
            pnpm run prod:db:migrate || exit

            echo "Building the app"
            pnpm run build || exit

            echo "Reloading the app with PM2 (zero-downtime)"
            pm2 reload ecosystem.config.cjs || exit

            # Save the PM2 process list for restarts
            pm2 save || exit
